docs: CoreProtectのドキュメントを追加
azisaba/AdminResources pull request #1
Opened 2022-07-31 12:08 UTC by m2en

2022-07-31 12:09 UTC, m2en commented
疲れたわ 💢

2022-08-01 09:26 UTC, acrylic-style requested changes

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +e.x `/co purge t:30d r:#world_nether`
e.xという単語も略語も存在しないので、別のに置き換える
```suggestion
e.g. `/co purge t:30d r:#world_nether`
```
```suggestion
例: `/co purge t:30d r:#world_nether`
```
```suggestion
Example: `/co purge t:30d r:#world_nether`
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +### ルックアップ
ルックアップという単語はあるけど見慣れてない人が多いと思われるので、日本語に置き換えたらどうか
```suggestion
### 検索
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +  - ねぼすけのMCID変更履歴を表示します。
説明にはニックネーム(`さいろんこ`など)ではなくそのままMCIDを使用したほうがいい。ニックネームの意味が分からない人や通じない人も当然いるはずだし、いきなりニックネームが出てくると混乱する可能性がある。

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`/co lockup` は一般にロールバックコマンドと同じですが、主な違いはデフォルトの半径がルックアップに適用されません。
lookupの誤字の修正と補足
```suggestion
`/co lookup` の引数は一般にロールバックコマンドと同じですが、主な違いはデフォルトの半径がルックアップに適用されません。
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +  - この場合は さいろんこ(`siloneco`)・たけのこ(`takenekooon`)というMCIDのログのみを検索します。
ニックネームの使用はなるべく避けよう

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +ゲーム内(Minecraft)で使用した場合は --30日以上前のデータのみ-- 削除することができ、コンソールから使用した場合は --24時間以上前のデータのみ-- を削除することができます。
```suggestion
ゲーム内(Minecraft)で使用した場合は**30日以上前のデータのみ**削除することができ、コンソールから使用した場合は**24時間以上前のデータのみ**を削除することができます。
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +![Lockup](../image/195320.png)
```suggestion
## Lookup(ルックアップ)

`/co lookup` (or `/co l` ) で使えるモード。

Inspectorとは違い、ログを正確に検索することができます。

Inspectorモードでは調べられない場所や範囲を広げて検索するときに役立ちます。

| コマンド | パラメーター |
| ---- | ---- |
| `/co lookup` | `(u:<user> t:<time> r:<radius> a:<action> i:<include> e:<exclude> | ページ)` |
| `/co l` | `/co lookup <params>` |

![Lookup](../image/195320.png)
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +古いブロックデータをパージ(削除)します。古いデータを使用しない場合、HDD(SSD)の空き容量を確保するのに便利です。
```suggestion
古いブロックデータをパージ(削除)します。古いデータを使用しない場合、ストレージの空き容量を確保するのに便利です。
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +(普段から使うコマンドではありません。)
```suggestion
```
不可逆的な操作であることを付け加えるといいと思う。

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`#optimize` を使用するとパージの速度が著しく低下するので通常は不要なオプションであることに注意してください。
これだとデメリットしかないように見える上に最適化でなにが起こるかが記載されてないので、「rollbackなどの操作が遅い場合は`#optimize`を使用すると操作が軽くなる場合があります。」と書くといいと思う。

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +以下のコマンドではパラメーターで、オプションなどを詳細的に指定する必要があります。
「詳細的」とは日本語であまり言わない気がする

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +- `/co lockup`
```suggestion
- `/co lookup`
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +ロールバックするとInteractive・Lockupで参照するログには横線が入り、操作が行われたことがわかるようになっています。
```suggestion
ロールバックするとInteractive・Lookupで参照するログには横線が入り、操作が行われたことがわかるようになっています。
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +| `/co lockup` | `u:<user> t:<time> r:<radius> a:<action> i:<include> e:<exclude>` |
```suggestion
| `/co lookup` | `u:<user> t:<time> r:<radius> a:<action> i:<include> e:<exclude>` |
```

2022-08-01 09:26 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`/co lockup` (or `/co l` ) で使えるモード。
```suggestion
## Lookup(ルックアップ)

`/co lookup` (or `/co l` ) で使えるモード。
```

2022-08-10 07:54 UTC, acrylic-style requested changes
`/co undo`と`/co near`も書いた方がよさそう

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +![Lockup](../image/195320.png)
Lockupあとひとつ
```suggestion
![Lookup](../image/195320.png)
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +  - 3日間以内の_Be4_のインベントリのログを表示します。
斜体になっているのを修正(ほかのMCIDも同じように修正したほうがいいかも?)
```suggestion
  - 3日間以内の`_Be4_`のインベントリのログを表示します。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +  - 1時間以内にダイヤモンドの斧で破壊したブロックのログを表示します。
```suggestion
  - 1時間以内のダイヤモンドの鉱石を破壊したログを表示します。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +  - 1時間以内にm2enがサーバー全体で破壊・設置した石ブロックと土ブロックをロールバックします。
`石ブロックと土ブロック` -> `石ブロックと土ブロック以外`?

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +### `i:<include>`
ちなみに`block:なんとか`(`b:なんとか`)も使用可能。効果は私が知ってる限りではincludeと同じ。

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +古いブロックデータをパージ(削除)します。古いデータを使用しない場合、ストレージの空き容量を確保するのに便利です。
```suggestion
古いログをパージ(削除)します。古いデータを使用しない場合、ストレージの空き容量を確保するのに便利です。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`/co rollback` (or `/co rb` )で使用できるモード。
余分なスペースを削除
```suggestion
`/co rollback` (or `/co rb`)で使用できるモード。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`/co lookup` (or `/co l` ) で使えるモード。
スペース削除
```suggestion
`/co lookup` (or `/co l`) で使えるモード。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +`/co i` (or `/co inspect` ) で使えるモード。
スペース削除
```suggestion
`/co i` (or `/co inspect`) で使えるモード。
```

2022-08-10 07:54 UTC, acrylic-style commented on docs/plugins/CoreProtect.md
> +## consumer
小文字 -> 大文字
```suggestion
## Consumer
```

2022-08-14 07:21 UTC, acrylic-style approved these changes
probably ok

2022-08-14 08:50 UTC, acrylic-style commented
ただ個人的に実際に処罰されている一般のプレイヤーを例として出すのはどうかと思う。

2022-08-14 09:05 UTC, m2en commented
> ただ個人的に実際に処罰されている一般のプレイヤーを例(画像)として出すのはどうかと思う。

確かに
消す

2022-08-14 09:16 UTC, acrylic-style commented
@siloneco ざっと目を通して問題がなければマージしていいよ

2022-08-14 12:47 UTC, siloneco requested changes

2022-08-14 12:47 UTC, siloneco commented on docs/plugins/CoreProtect.md
> +ロールバックするとInteractive・Lookupで参照するログには横線が入り、操作が行われたことがわかるようになっています。
```suggestion
ロールバックするとInspector・Lookupで参照するログには横線が入り、操作が行われたことがわかるようになっています。
```
Inspectorじゃない？

2022-08-14 12:47 UTC, siloneco commented on docs/plugins/CoreProtect.md
> +時間については `u:<user>` と同じように複数指定(組み合わせ)することができ、少数を使用することも可能です。
```suggestion
時間については `u:<user>` と同じように複数指定(組み合わせ)することができ、小数を使用することも可能です。
```

2022-08-14 12:47 UTC, siloneco commented on docs/plugins/CoreProtect.md
> +プレイヤー一から半径何ブロック以内を対象にするかを数値で指定します。
```suggestion
プレイヤー位置から半径何ブロック以内を対象にするかを数値で指定します。
```

2022-08-14 14:37 UTC, siloneco approved these changes

2022-08-14 14:38 UTC, merged