あっぷでーと MythicMobs.md 👍🏻
azisaba/AdminResources pull request #3
Opened 2022-08-14 17:27 UTC by H4RuCat

あっぷでーとした

2022-08-14 22:34 UTC, acrylic-style requested changes

2022-08-14 22:34 UTC, acrylic-style commented on docs/plugins/MythicMobs.md
> +MovementSpeed: [number] #(移動速度上昇)
スペース6個入れた方がいいかも？

2022-08-14 22:34 UTC, acrylic-style commented on docs/plugins/MythicMobs.md
> +### ・Skills
```suggestion
### Skills
```

2022-08-14 22:34 UTC, acrylic-style commented on docs/plugins/MythicMobs.md
> +### ・Item ※MythicCruicible必須
```suggestion
### Item

この機能を利用するにはMythicCruicibleまたはMythicArtifactsが必要です。
```

2022-08-14 22:34 UTC, acrylic-style commented on docs/plugins/MythicMobs.md
> +### ・Mob
```suggestion
### Mob
```

2022-08-14 22:34 UTC, acrylic-style commented on docs/plugins/MythicMobs.md
> +アジ鯖内でMMを使用するときは(恐らく)関係ないですが、アイテムを作成するときは別Plugin(MythicCrucible)が必要です。
```suggestion
アイテムを作成するときは別Plugin(MythicCrucibleもしくはMythicArtifacts)が必要です。
```

2022-08-20 04:39 UTC, acrylic-style approved these changes

2022-08-20 12:11 UTC, siloneco requested changes

2022-08-20 12:11 UTC, siloneco commented on docs/plugins/MythicMobs.md
> +|  ターゲッター  |  略称系  |  説明  |
```suggestion
|  ターゲッター  |  省略形  |  説明  |
```
同様にあと11か所も要修正

2022-08-20 12:11 UTC, siloneco commented on docs/plugins/MythicMobs.md
> +|  overheal  |  oh  |  限界突破☆して回復するか  |
```suggestion
|  overheal  |  oh  |  限界突破して回復するか  |
```

2022-08-20 12:11 UTC, siloneco commented on docs/plugins/MythicMobs.md
> +|  Points  |  p  |  軌道を構成する点の数。  |
```suggestion
|  Points  |  p  |  軌道を構成する点の数  |
```

2022-08-20 12:11 UTC, siloneco commented on docs/plugins/MythicMobs.md
> +`/mm relaoad`
```suggestion
`/mm reload`
```

2022-08-21 23:56 UTC, siloneco commented
反応なさそうなら数日後に勝手に編集して勝手にマージする

2022-08-23 14:48 UTC, siloneco approved these changes

2022-08-23 14:48 UTC, merged